services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:80"
    volumes:
      - ./task-1:/var/www/html 
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_registration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./task-1/db/init.sql:/docker-entrypoint-initdb.d/init.sql
