version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_registration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3305"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql